export const surpriseMePrompts = [
  'a teacup shaped like a dragon egg, glowing softly',
  'a surrealist watercolor of a whale playing the piano under moonlight',
  'samurai rabbits practicing archery in a bamboo forest, ukiyo-e style',
  'a Van Gogh-inspired oil painting of a robot tending a flower garden',
  'koala alchemist brewing potions in a neon-lit lab, digital art',
  'a macro shot of two ants in tiny tuxedos dancing on a leaf, digital art',
  '3D render of a jellyfish floating in a cosmic galaxy, digital art',
  'a cyborg relaxing on a hammock in a Martian oasis, synthwave',
  'a regal oil painting of a llama in Victorian attire with a golden monocle',
  'a mosaic depicting a sushi roll and chopsticks in vibrant colors',
  'a charcoal sketch of a floating city with hoverbikes in a stormy sky',
  'a cozy café with a pool of emerald water and another of shimmering gold, digital art',
  'a mystical corgi reading tarot cards in a crystal cave, digital art',
  '"a peacock with a diamond tiara" in the style of Gustav Klimt',
  'a chalk drawing of a grumpy owl piloting a hot air balloon',
  'a painting of a wolf howling under a swirling aurora borealis',
  'a knitted tapestry of a pizza slice with glowing eyes',
  'a plush toy dragon curled up in a sunlit meadow',
  'a retro-futuristic sunset over a desert with glowing cacti, digital art',
  'a pair of glass skyscrapers connected by a bridge of vines, digital art',
  'a 3D render of a pastel-colored sailboat drifting on a misty lake',
  'a manga-style cover of a robot hero wielding a glowing katana',
  'a vibrant splash of glitter paint on a white canvas',
  'a photo of a husky and a tabby cat napping together in a hammock',
  'a photo of a fluffy blue creature lounging in a green room',
  'a photo of a Greek statue playing an electric guitar',
  'a ninja surfing on a comet in deep space, lomography',
  'a vintage Mustang cruising along the Pacific Coast Highway at dusk, 50mm photography',
  'a realistic portrait of a young man with green eyes and dark hair',
  'a woman stepping through a portal to a lush jungle dimension',
  'Patrick Star in a noir detective film, black and white',
  'a triceratops selling ice cream cones in a park, lomography',
  'a woman walking through a vibrant Seoul market at night, 50mm lens',
  'a living taco dancing in a vibrant Mexican festival, Pixar style',
  'a neon-lit robot karaoke bar in a futuristic city',
  'a lost 1980s anime of a Gundam-inspired mech battle',
  'a sushi platter shaped like a chessboard, professional food photography',
  'a cyberpunk armadillo glowing in a rainy alley, Blade Runner style',
  'an astronaut meeting a bioluminescent creature in a cave, photography',
  'a saber-toothed cat roaming the streets of Paris, photography',
  'a woman bonding with her sentient AI hologram, digital art',
  'a photo of a cyborg monk meditating in Kyoto at dawn, lomography',
  'a vampire strolling through 1930s Chicago, sepia photography',
  'a synthwave submarine gliding through a coral reef',
  'a man wandering through a snowy Osaka alley with neon signs, 50mm',
  'a rocket soaring over the pyramids of Giza, digital art',
];