const express = require("express");
const dotenv = require("dotenv");
const FormData = require("form-data");
const fetch = (...args) => import("node-fetch").then(({ default: fetch }) => fetch(...args));

dotenv.config();

const router = express.Router();

router.get("/", async (req, res) => {
  res.status(200).json({ message: "Hello from AI!" });
});

// POST route for image generation
router.post("/", async (req, res) => {
  try {
    if (!req.body || !req.body.prompt) {
      console.log("Invalid or missing request body:", req.body);
      return res.status(400).json({ error: "Prompt is required in the request body" });
    }

    const { prompt } = req.body;

    if (!process.env.CLIPDROP_API_KEY) {
      console.error("CLIPDROP_API_KEY is not set in environment variables");
      return res.status(500).json({ error: "API key not configured" });
    }

    const controller = new AbortController();
    const timeoutId = setTimeout(() => {
      console.log("Clipdrop API request timed out");
      controller.abort();
    }, 60000); // 1 minute timeout

    console.log(`Generating image with prompt: "${prompt}"`);

    // Create FormData and append the prompt
    const form = new FormData();
    form.append('prompt', prompt);
    
    // Clipdrop API URL
    const clipdropUrl = 'https://clipdrop-api.co/text-to-image/v1';
    
    console.log(`Requesting from: ${clipdropUrl}`);

    const response = await fetch(clipdropUrl, {
      method: "POST",
      headers: {
        'x-api-key': process.env.CLIPDROP_API_KEY,
      },
      body: form,
      signal: controller.signal,
    });

    clearTimeout(timeoutId);

    console.log('Response status:', response.status);

    if (!response.ok) {
      const error = await response.text();
      console.error("Clipdrop API Error:", error);
      return res.status(500).json({ error: `Clipdrop API Error: ${error}` });
    }

    // Get the image as buffer
    const arrayBuffer = await response.arrayBuffer();
    
    if (arrayBuffer.byteLength === 0) {
      console.error("Empty response from Clipdrop API");
      return res.status(500).json({ error: "Empty response from Clipdrop API" });
    }

    // Convert to base64
    const base64Image = Buffer.from(arrayBuffer).toString("base64");
    console.log("Image generated successfully with Clipdrop API");

    res.status(200).json({ 
      photo: base64Image,
      service: "Clipdrop API"
    });

  } catch (err) {
    console.error("Server Error:", err.message, err.stack);
    
    if (err.name === 'AbortError') {
      return res.status(408).json({ error: "Request timed out. Please try again." });
    }
    
    res.status(500).json({ error: err.message || "Something went wrong" });
  }
});

module.exports = router;

// Image generated by Clipdrop API is fetched as binary data
// and converted to base64 string to send back to the client
// The client then decodes the base64 string and displays the image
