const express = require("express");
const dotenv = require("dotenv");
const fetch = (...args) => import("node-fetch").then(({ default: fetch }) => fetch(...args));

dotenv.config();

const router = express.Router();

router.get("/", async (req, res) => {
  res.status(200).json({ message: "Hello from AI!" });
});

// POST route for image generation
router.post("/", async (req, res) => {
  try {
    if (!req.body || !req.body.prompt) {
      console.log("Invalid or missing request body:", req.body);
      return res.status(400).json({ error: "Prompt is required in the request body" });
    }

    const { prompt } = req.body;

    const controller = new AbortController();
    const timeoutId = setTimeout(() => {
      console.log("Hugging Face API request timed out");
      controller.abort();
    }, 90000);

    const randomSeed = Math.floor(Math.random() * 1000000);

    const response = await fetch(
      "https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-xl-base-1.0",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${process.env.HUGGINGFACE_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          inputs: prompt,
          parameters: {
            num_inference_steps: 25,
            guidance_scale: 7.5,
            seed: randomSeed, //random seed for variability
          },
        }),
        signal: controller.signal,
      }
    );

    clearTimeout(timeoutId);

    if (!response.ok) {
      const error = await response.text();
      console.error("Hugging Face API Error:", error);
      return res.status(500).json({ error: `Hugging Face API Error: ${error}` });
    }

    const arrayBuffer = await response.arrayBuffer();
    if (arrayBuffer.byteLength === 0) {
      console.error("Empty response from Hugging Face API");
      return res.status(500).json({ error: "Empty response from Hugging Face API" });
    }

    const base64Image = Buffer.from(arrayBuffer).toString("base64");

    res.status(200).json({ photo: base64Image });
  } catch (err) {
    console.error("Server Error:", err.message, err.stack);
    res.status(500).json({ error: err.message || "Something went wrong" });
  }
});

module.exports = router;

//image generated by hugging face api is in binary format which is then converted to base64 string and sent back to the client
//the client then decodes the base64 string and displays the image